global:
  smtp_from: "olakunleawonusi@gmail.com"
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: "olakunleawonusi@gmail.com"
  smtp_auth_identity: "olakunleawonusi@gmail.com"
  smtp_auth_password: "oeueyhonjtlbofho"

route:
  # Default Receiver, Fallback Receiver
  receiver: admin
  group_by: ["category"]
  routes:
    # Route for OS Alerts
    - match_re:
        app_type: (linux|windows)
      # Fallback Receiver for OS Alerts
      receiver: abc_sol-admin
      routes:
        - match:
            app_type: linux
          # Fallback Receiver for Linux Alerts
          receiver: abc_sol_linux-admin
          routes:
            - match:
                severity: critical
              receiver: abc_sol_linux-manager
              continue: true

            - match:
                severity: warning
              receiver: abc_sol_linux-teamlead
              continue: true

            - match:
                category: cpu
              receiver: abc_sol_linux-cpu

        - match:
            app_type: windows
          # Fallback Receiver for Windows Alerts
          receiver: abc_sol_windows-admin
          routes:
            - match:
                severity: critical
              receiver: abc_sol_windows-manager

            - match:
                severity: warning
              receiver: abc_sol_windows-teamlead     

    # Route for Application Alerts
    - match_re:
        app_type: (python|go)
      # Fallback Receiver for Application Alerts
      receiver: xyz_sol-admin
      routes:
        - match:
            app_type: python
          # Fallback Receiver for Python Alerts
          receiver: xyz_sol_python-admin
          routes:
            - match:
                severity: critical
              receiver: xyz_sol_python-manager

            - match:
                severity: warning
              receiver: xyz_sol_python-teamlead


        - match:
            app_type: go
          # Fallback Receiver for Go Alerts
          receiver: xyz_sol_go-admin 
          routes:
            - match:
                severity: critical
              receiver: xyz_sol_go-manager

            - match:
                severity: warning
              receiver: xyz_sol_go-teamlead

receivers:
  - name: admin
    email_configs:
      - to: "teeman76@yahoo.com"

  - name: abc_sol-admin
    email_configs:
      - to: "admin@abc-solution.com"

  - name: abc_sol_linux-admin
    email_configs:
      - to: "linux.admin@abcsolution.com"

  - name: abc_sol_linux-manager
    email_configs:
      - to: "linux.manager@abcsolution.com"

  - name: abc_sol_linux-teamlead
    email_configs:
      - to: "linux.teamlead@abcsolution.com"

  - name: abc_sol_linux-cpu
    email_configs:
      - to: "linux.teamcpu@abcsolution.com"

  - name: abc_sol_windows-admin
    email_configs:
      - to: "windows.admin@abcsolution.com"

  - name: abc_sol_windows-manager
    email_configs:
      - to: "windows.manager@abcsolution.com"

  - name: abc_sol_windows-teamlead
    email_configs:
      - to: "windows.teamlead@abcsolution.com"

  - name: xyz_sol-admin
    email_configs:
      - to: "admin@xyzsolution.com"

  - name: xyz_sol_python-admin
    email_configs:
      - to: "python.admin@xyzsolution.com"

  - name: xyz_sol_python-manager
    email_configs:
      - to: "python.manager@xyzsolution.com"

  - name: xyz_sol_python-teamlead
    email_configs:
      - to: "python.teamlead@xyzsolution.com"

  - name: xyz_sol_go-admin
    email_configs:
      - to: "go.admin@xyzsolution.co"

  - name: xyz_sol_go-manager
    email_configs:
      - to: "go.manager@xyzsolution.com"

  - name: xyz_sol_go-teamlead
    email_configs:
      - to: "go.teamlead@xyzsolution.com"